# Generated by Django 4.0.5 on 2022-06-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='employeeid',
        ),
    ]
