# Generated by Django 4.0.5 on 2022-06-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_index_concern_alter_index_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='concern',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='index',
            name='department',
            field=models.TextField(default='no information', max_length=100),
        ),
        migrations.AlterField(
            model_name='index',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
    ]
