# Generated by Django 4.0.5 on 2022-06-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_index_concern_alter_index_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='department',
        ),
    ]
