# Generated by Django 4.0.5 on 2022-06-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_index_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='concern',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='index',
            name='emailid',
            field=models.CharField(default='0', max_length=120),
        ),
        migrations.AlterField(
            model_name='index',
            name='fullname',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
