# Generated by Django 4.0.5 on 2022-06-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_index_concern_alter_index_emailid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='emailid',
            field=models.CharField(blank=True, default='', max_length=110),
        ),
    ]
